version: "3"

services:
  #service: definition of mysql database
  dockerdb:
    image: mysql:5.7

    container_name: dockerdb

    environment:
      MYSQL_DATABASE: docker_pms_db
      MYSQL_USER: root
      MYSQL_PASSWORD: Vwpassatb5.5
      MYSQL_ROOT_PASSWORD: Vwpassatb5GP

    ports:
    - "3307:3306"

    restart: always