version: "3.7"

services:
  #service: definition of mysql database
  db:
    image: mysql:latest
    container_name: docker_db
    environment:
      - MYSQL_ROOT_PASSWORD=Vwpassatb5.5
      - MYSQL_USER=root
    ports:
    - "3306:3306"
    restart: always